name: "Deploy Project"
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout project"
              uses: "actions/checkout@v3"
            - name: "Install node.js"
              uses: "actions/setup-node@v3"
              with:
                node-version: 18
            - name: "Install node dependancies"
              run: npm ci
            - name: "Lint"
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: "Checkout project"
              uses: "actions/checkout@v3"
            - name: "Install node.js"
              uses: "actions/setup-node@v3"
              with:
                node-version: 18
            - name: "Install node dependancies"
              run: npm ci
            - name: "Run tests"
              run: npm run test
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: "Checkout project"
              uses: "actions/checkout@v3"
            - name: "Install node.js"
              uses: "actions/setup-node@v3"
              with:
                node-version: 18
            - name: "Install node dependancies"
              run: npm ci
            - name: "Build"
              run: npm run build
            - name: "Deploy"
              run: echo "Deploying..."
    